In [1]:
import json
import numpy as np
import pandas as pd
import os

In [3]:
filename = []
for i in os.listdir("D:碩士課程//json"):
    filename.append(i)
filename.sort(reverse = True)

In [29]:
#print(filename)
DF_list = []
for df in filename:
    DF_list.append(filename[:-5])
print(DF_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [25]:
#-----------Stored trainning data--------------
fro = filename.index('2017-06-01.json')
to = filename.index('2017-09-30.json')

DF = {}
for i in range(to,fro+1):
    with open('D:碩士課程//json//'+filename[i]) as f:
        symbol_f = json.load(f)
    DF[filename[i][:-5]] = symbol_f
    f.close()

#--------------load all data-------------------
'''
for i in filename[5:]:
    with open('json/'+i) as f:
        symbol_f = json.load(f)
    DF[i[:-5]] = symbol_f
    f.close()
'''
#print(DF['2018-09-25'])

"\nfor i in filename[5:]:\n    with open('json/'+i) as f:\n        symbol_f = json.load(f)\n    DF[i[:-5]] = symbol_f\n    f.close()\n"

In [33]:
#------------Stored testing data---------------
files_recent = {}
fr_list = []
for j in filename[:5]:
    fr_list.append(j[:-5])
    with open('D:碩士課程//json//'+j) as f:
        symbol_f = json.load(f)
    files_recent[j[:-5]] = symbol_f
    f.close
print(files_recent.keys())
print(fr_list)

dict_keys(['2018-10-02', '2018-10-01', '2018-09-28', '2018-09-27', '2018-09-26'])
['2018-10-02', '2018-10-01', '2018-09-28', '2018-09-27', '2018-09-26']

In [39]:
#print(DF['2017-06-01'])
#print(DF['2017-08-31'])

In [20]:
day = [d[:-5] for d in filename]
Stock_sym = [sym for sym in files_recent[fr[0]].keys()]
Stock_sym.remove('id')
new_Stock_list = []
Ans = []
Open = []
Stock_feature = []


stock_attr = []
for symbol in Stock_sym:
    stock_attr = Stock_selec(files_recent,fr_list,symbol)
    if len(tmp) != 30:
        continue
    if files_recent[fr_list[0]][symbol]['close'] != 'NULL' and files_recent[fr_list[0]][symbol]['close'] != None:
        new_Stock_list.append(symbol)
        Ans = float(files_recent[fr_list[-1-i]][Stock]['close'])
        O = float(test[Day_list[-1-i]][Stock]['open'])
        Stock_feature.append(tmp)
        Answer.append(Ans)
        Open.append(O)

9958

In [43]:
def Stock_selec(file, file_list,symbol):
    tmp = []
    for i in range(0, 5):
        if symbol not in file[file_list[i]].keys():
            break
        for attr in ['open', 'close', 'high', 'low', 'adj_close', 'volume']:
            if file[file_list[i]][Stock][attr] == None:
                break
            if file[file_list[i]][Stock][attr] == 'NULL':
                break
            tmp.append(float(file[file_list[i]][Stock][attr])) 
    return tmp

In [ ]:
for Stock in Stock_list:
    tmp = []
    for i in range(0, 5):
        if Stock not in test[Day_list[-1-i]].keys():
            break
        for attr in ['open', 'close', 'high', 'low', 'adj_close', 'volume']:
            if test[Day_list[-1-i]][Stock][attr] == None:
                break
            if test[Day_list[-1-i]][Stock][attr] == 'NULL':
                break
            tmp.append(float(test[Day_list[-1-i]][Stock][attr]))    
    if len(tmp) != 30:
        continue
    if test[Day_list[-1]][Stock]['close'] != 'NULL' and test[Day_list[-1]][Stock]['close'] != None:
        new_Stock_list.append(Stock)
        Ans = float(test[Day_list[-1-i]][Stock]['close'])
        O = float(test[Day_list[-1-i]][Stock]['open'])
        Stock_feature.append(tmp)
        Answer.append(Ans)
        Open.append(O)

In [16]:
DF[0] = pd.DataFrame(DF[0])
DF[0].head(6)

,0050,0051,0052,0053,0054,0055,0056,0057,0058,0059,...,9939,9940,9941,9942,9943,9944,9946,9955,9958,id
adj_close,86.00,32.79,54.85,36.08,23.55,18.62,27.20,52.00,47.76,44.92,...,51.40,33.75,101.50,78.60,58.40,16.15,13.35,13.85,90.00,2018-10-02
close,86.05,32.80,55.15,36.15,23.64,18.65,27.20,52.25,48.08,45.32,...,51.50,33.80,101.50,78.60,58.40,16.25,13.35,13.95,90.00,2018-10-02
high,87.25,32.95,55.60,36.61,23.84,18.90,27.32,52.25,48.39,45.38,...,51.70,33.85,102.00,80.00,58.90,16.30,13.40,14.00,94.60,2018-10-02
low,86.00,32.80,55.15,36.13,23.64,18.63,27.13,52.25,47.94,45.32,...,51.30,33.70,101.50,78.60,58.30,16.15,13.35,13.65,89.10,2018-10-02
open,87.25,32.95,55.60,36.61,23.84,18.90,27.32,52.25,48.39,45.38,...,51.60,33.80,101.50,79.70,58.90,16.15,13.40,13.75,94.60,2018-10-02
volume,5434332,21000,101609,20000,4000,100034,1966764,20000,23000,2000,...,315956,98608,116440,22100,93609,26050,130169,27387,19924320,2018-10-02